// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace WebTextEditor.DAL.Sql.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DocumentContentValue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DocumentContentValue));
        
        string IMigrationMetadata.Id
        {
            get { return "201505192322220_DocumentContentValue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
